### ISSUE TITLE
What are the pickle files?

### ISSUE THREAD

**Issue by DanielAndreasen** [mveyette/analyze_NIRSPEC1#1]
Hi Mark,

Very nice work, we will go through your paper tomorrow for a journal club :)
I wonder what the `.pkl` file contains. Especially the one you use in `example.py`.

And nice job sharing your work on github! It is always appreciated.

Cheers,
Daniel

**Comment by mveyette** [comment]
Hi Daniel,

Thanks for the question. I admit I did not spend a whole lot of time making this code user-friendly because of its very limited application. The two pickle files are described below.

PM_I18007+2933.pkl - This is just the extracted NIRSPEC-1 spectrum for one of the M dwarfs in our calibration sample. I include it so that you can test out the code on a spectrum I have already analyzed.

Models_ews.pkl - These are line equivalents widths measured from our grid of synthetic spectra. The full spectra are available on my site here: <http://people.bu.edu/mveyette/phoenix/>

**Comment by DanielAndreasen** [comment]
I understand you. Anyway, thanks for answering my question. That was helpful.
